// webui/src/App.svelte
<script>
  import { onMount } from 'svelte';
  import { exec } from 'kernelsu';
  import locate from './locate.json';
  import './app.css';

  const DEFAULT_CONFIG = {
    moduledir: '/data/adb/modules',
    tempdir: '',
    mountsource: 'KSU',
    logfile: '/data/adb/magic_mount/mm.log',
    verbose: false,
    partitions: []
  };

  const CONFIG_PATH = '/data/adb/magic_mount/mm.conf';

  // i18n
  let lang = 'en';
  $: L = locate[lang];
  
  // Autoload lang 
  const availableLanguages = Object.keys(locate).map(code => ({
    code,
  name: locate[code]?.lang?.display || code.toUpperCase()
  }));

  let langDropdownOpen = false;

  function toggleLangDropdown() {
    langDropdownOpen = !langDropdownOpen;
  }

  function selectLanguage(newLang) {
    lang = newLang;
    langDropdownOpen = false;
    if (typeof window !== 'undefined') {
      window.localStorage.setItem('mm-lang', newLang);
    }
  }

  function handleClickOutside(event) {
    const dropdown = event.target.closest('.lang-dropdown');
    if (!dropdown && langDropdownOpen) {
      langDropdownOpen = false;
    }
  }

  // tabs
  let activeTab = 'config';
  let isSwitching = false;

  function switchTab(tab) {
    if (tab === activeTab || isSwitching) return;

    isSwitching = true;

    setTimeout(() => {
      activeTab = tab;
      isSwitching = false;
    }, 300);
  }


  // config state
  let config = { ...DEFAULT_CONFIG };
  let configLoading = false;
  let configSaving = false;
  let configMessage = null;

  // log state
  let logSelection = 'current';
  let logContent = '';
  let logLoading = false;
  let logError = null;

  // partitions input
  let partitionInput = '';

  // modules state
  let modules = [];
  let modulesLoading = false;
  let modulesError = null;

  // helpers
  function isTrueValue(v) {
    const s = v.trim().toLowerCase();
    return s === '1' || s === 'true' || s === 'yes' || s === 'on';
  }

  function parseKvConfig(text) {
    try {
      const result = { ...DEFAULT_CONFIG };
      const lines = text.split('\n');

      for (let line of lines) {
        line = line.trim();
        if (!line || line.startsWith('#')) continue;

        const eqIndex = line.indexOf('=');
        if (eqIndex < 0) continue;

        let key = line.slice(0, eqIndex).trim();
        let value = line.slice(eqIndex + 1).trim();

        if (!key || !value) continue;

        switch (key) {
          case 'module_dir':
            result.moduledir = value;
            break;
          case 'temp_dir':
            result.tempdir = value;
            break;
          case 'mount_source':
            result.mountsource = value;
            break;
          case 'log_file':
            result.logfile = value;
            break;
          case 'debug':
            result.verbose = isTrueValue(value);
            break;
          case 'partitions':
            result.partitions = value
              .split(',')
              .map(s => s.trim())
              .filter(s => s.length > 0);
            break;
        }
      }

      return result;
    } catch (e) {
      console.error('Failed to parse config:', e);
      return null;
    }
  }

  function serializeKvConfig(cfg) {
    const lines = ['# Magic Mount Configuration File', '# Generated by Web UI', ''];

    const moduleDir = cfg.moduledir || DEFAULT_CONFIG.moduledir;
    const mountSource = cfg.mountsource || DEFAULT_CONFIG.mountsource;
    const logFile = cfg.logfile || DEFAULT_CONFIG.logfile;

    lines.push(`module_dir=${moduleDir}`);

    if (cfg.tempdir) {
      lines.push(`temp_dir=${cfg.tempdir}`);
    }

    lines.push(`mount_source=${mountSource}`);

    if (logFile) {
      lines.push(`log_file=${logFile}`);
    }

    lines.push(`debug=${cfg.verbose ? 'true' : 'false'}`);

    if (cfg.partitions.length > 0) {
      lines.push(`partitions=${cfg.partitions.join(',')}`);
    }

    return lines.join('\n');
  }

  // load config
  async function loadConfig() {
    configLoading = true;
    configMessage = null;

    try {
      const { errno, stdout, stderr } = await exec(
        `[ -f "${CONFIG_PATH}" ] && cat "${CONFIG_PATH}" || echo ""`
      );

      if (errno !== 0) {
        console.error(stderr);
        config = { ...DEFAULT_CONFIG };
        partitionInput = '';
        configMessage = L.config.loadError;
        return;
      }

      if (!stdout.trim()) {
        config = { ...DEFAULT_CONFIG };
        partitionInput = '';
        configMessage = L.config.loadDefault;
        return;
      }

      const parsed = parseKvConfig(stdout);
      if (parsed) {
        config = parsed;
        partitionInput = parsed.partitions.join(', ');
        configMessage = L.config.loadSuccess;
      } else {
        config = { ...DEFAULT_CONFIG };
        partitionInput = '';
        configMessage = L.config.loadError;
      }
    } catch (e) {
      console.error(e);
      config = { ...DEFAULT_CONFIG };
      partitionInput = '';
      configMessage = L.config.loadError;
    } finally {
      configLoading = false;
    }
  }

  // save config
  async function saveConfig() {
    configSaving = true;
    configMessage = null;

    try {
      const partitions = partitionInput
        .split(',')
        .map(s => s.trim())
        .filter(s => s);

      const configToSave = { ...config, partitions };

      const content = serializeKvConfig(configToSave);
      const escapedContent = content.replace(/'/g, "'\\''");

      const shell = `
        mkdir -p "$(dirname "${CONFIG_PATH}")" && \
        printf '%s\n' '${escapedContent}' > "${CONFIG_PATH}"
      `;

      const { errno, stderr } = await exec(shell);

      if (errno !== 0) {
        console.error(stderr);
        configMessage = L.config.saveFailed;
      } else {
        config = configToSave;
        configMessage = L.config.saveSuccess;
      }
    } catch (e) {
      console.error(e);
      configMessage = L.config.saveError;
    } finally {
      configSaving = false;
    }
  }

  // load log
  async function loadLog() {
    logLoading = true;
    logError = null;
    logContent = '';
    try {
      const basePath = config.logfile || DEFAULT_CONFIG.logfile;
      const fullPath = logSelection === 'current' ? basePath : `${basePath}.old`;

      const { errno, stdout, stderr } = await exec(
        `[ -f "${fullPath}" ] && cat "${fullPath}" || echo "Log file not found"`
      );

      if (errno !== 0) {
        console.error(stderr);
        logError = L.logs.readFailed + ` (errno=${errno})`;
      } else {
        logContent = stdout || '';
      }
    } catch (e) {
      console.error(e);
      logError = L.logs.readException;
    } finally {
      logLoading = false;
    }
  }

  // load modules
  async function loadModules() {
    modulesLoading = true;
    modulesError = null;
    modules = [];
    try {
      const moduleDir = config.moduledir || DEFAULT_CONFIG.moduledir;

      const shell = `
        MOD_DIR="${moduleDir}"
        [ -d "$MOD_DIR" ] || exit 0
        for m in "$MOD_DIR"/*; do
          [ -d "$m" ] || continue
          [ -d "$m/system" ] || continue
          name="$(basename "$m")"
          disabled=0
          skip=0
          if [ -e "$m/disable" ] || [ -e "$m/remove" ]; then
            disabled=1
          fi
          if [ -e "$m/skip_mount" ]; then
            skip=1
          fi
          printf '%s|%s|%s\n' "$name" "$disabled" "$skip"
        done
      `;

      const { errno, stdout, stderr } = await exec(shell);

      if (errno !== 0) {
        console.error(stderr);
        modulesError = L.modules.loadError;
        return;
      }

      const lines = stdout
        .split('\n')
        .map(l => l.trim())
        .filter(l => l.length > 0);

      modules = lines.map(line => {
        const [name, disabledStr, skipStr] = line.split('|');
        return {
          name: name || '(unknown)',
          disabledByFlag: disabledStr === '1',
          skipMount: skipStr === '1',
          toggling: false
        };
      });
    } catch (e) {
      console.error(e);
      modulesError = L.modules.loadError;
    } finally {
      modulesLoading = false;
    }
  }

  async function toggleSkipMount(event, mod) {
    if (mod.disabledByFlag) {
      event.target.checked = !event.target.checked;
      return
    };

    const moduleDir = config.moduledir || DEFAULT_CONFIG.moduledir;
    const modulePath = `${moduleDir}/${mod.name}`;

    modules = modules.map(m =>
      m.name === mod.name ? { ...m, toggling: true, error: undefined } : m
    );

    try {
      const shell = mod.skipMount
        ? `rm -f "${modulePath}/skip_mount"`
        : `touch "${modulePath}/skip_mount"`;

      const { errno, stderr } = await exec(shell);

      if (errno !== 0) {
        console.error(stderr);
        event.target.checked = !event.target.checked;
        modules = modules.map(m =>
          m.name === mod.name ? { ...m, toggling: false, error: L.modules.toggleError } : m
        );
      } else {
        modules = modules.map(m =>
          m.name === mod.name
            ? { ...m, skipMount: !m.skipMount, toggling: false, error: undefined }
            : m
        );
      }
    } catch (e) {
      console.error(e);
      event.target.checked = !event.target.checked;
      modules = modules.map(m =>
        m.name === mod.name ? { ...m, toggling: false, error: L.modules.toggleError } : m
      );
    }
  }

  onMount(() => {
    if (typeof window !== 'undefined') {
      const saved = window.localStorage.getItem('mm-lang');
      if (saved && locate[saved]) {
        lang = saved;
      }
      
      // 添加全局点击监听
      window.addEventListener('click', handleClickOutside);
      
      return () => {
        window.removeEventListener('click', handleClickOutside);
      };
    }
    loadConfig();
  });
  // reactive statements for tab changes
  let configLoaded = false;
  $: if (activeTab === 'config' && !configLoaded ) {
    loadConfig().then(() => {
      configLoaded = true;
    });
  }
  
  $: if (activeTab === 'log') {
    loadLog();
  }

  $: if (activeTab === 'module') {
    loadModules();
  }

  onMount(() => {
    if (typeof window !== 'undefined') {
      const saved = window.localStorage.getItem('mm-lang');
      if (saved && locate[saved]) {
        lang = saved;
      }
      
      window.addEventListener('click', handleClickOutside);
      
      return () => {
        window.removeEventListener('click', handleClickOutside);
      };
    }
  });

  $: effectiveModuleDir = config.moduledir || DEFAULT_CONFIG.moduledir;
</script>

<div class="app-root">
  <div class="top-bar">
    <div class="title">Magic Mount</div>
    
    <div class="lang-dropdown">
      <button 
        type="button" 
        class="lang-select" 
        on:click|stopPropagation={toggleLangDropdown}
      >
        {availableLanguages.find(l => l.code === lang)?.name || lang}
        <span class="arrow {langDropdownOpen ? 'open' : ''}">▼</span>
      </button>
      
      {#if langDropdownOpen}
        <div class="lang-menu">
          {#each availableLanguages as { code, name }}
            <button
              type="button"
              class="lang-option {code === lang ? 'active' : ''}"
              on:click={() => selectLanguage(code)}
            >
              {name}
            </button>
          {/each}
        </div>
      {/if}
    </div>
  </div>

  <div class="app-main">
    {#if isSwitching}
      <div class="tab-overlay">
          <div class="tab-spinner"></div>
      </div>
    {/if}

    {#key activeTab}
      {#if activeTab === 'config'}
        <div
          class="card"
          in:fade={{ duration: 180 }}
          out:fade={{ duration: 180 }}
        >
          <h2>{L.config.title}</h2>

          {#if configLoading}
            <p class="hint">Loading...</p>
          {/if}
          {#if configMessage}
            <p class="hint">{configMessage}</p>
          {/if}

          <div class="field">
            <label for="verbose-setting">{L.config.verboseLabel}</label>
            <div class="loglevel-switch" id="verbose-setting" role="group">
              <button
                type="button"
                class="lv-btn {!config.verbose ? 'active' : ''}"
                on:click|preventDefault={() => (config.verbose = false)}
              >
                {L.config.verboseOff}
              </button>
              <button
                type="button"
                class="lv-btn {config.verbose ? 'active' : ''}"
                on:click|preventDefault={() => (config.verbose = true)}
              >
                {L.config.verboseOn}
              </button>
            </div>
          </div>

          <div class="field">
            <label for="moduledir-input">{L.config.moduleDir}</label>
            <input
              id="moduledir-input"
              type="text"
              bind:value={config.moduledir}
              placeholder={DEFAULT_CONFIG.moduledir}
            />
          </div>

          <div class="field">
            <label for="tempdir-input">{L.config.tempDir}</label>
            <input
              id="tempdir-input"
              type="text"
              bind:value={config.tempdir}
              placeholder="(auto-select if empty)"
            />
          </div>

          <div class="field">
            <label for="mountsource-input">{L.config.mountSource}</label>
            <input
              id="mountsource-input"
              type="text"
              bind:value={config.mountsource}
              placeholder={DEFAULT_CONFIG.mountsource}
            />
          </div>

          <div class="field">
            <label for="logfile-input">{L.config.logFile}</label>
            <input
              id="logfile-input"
              type="text"
              bind:value={config.logfile}
              placeholder={DEFAULT_CONFIG.logfile}
            />
          </div>

          <div class="field">
            <label for="partitions-input">{L.config.extPartitions}</label>
            <input
              id="partitions-input"
              type="text"
              bind:value={partitionInput}
              placeholder="mi_ext,my_stock"
            />
          </div>

          <div class="actions">
            <button type="button" on:click|preventDefault={loadConfig} disabled={configLoading || configSaving}>
              {L.config.reload}
            </button>
            <button type="button" class="primary" on:click|preventDefault={saveConfig} disabled={configSaving || configLoading}>
              {configSaving ? 'Saving...' : L.config.save}
            </button>
          </div>

          <p class="path">{L.config.pathLabel}: {CONFIG_PATH}</p>
        </div>

      {:else if activeTab === 'module'}
        <div
          class="card"
          in:fade={{ duration: 180 }}
          out:fade={{ duration: 180 }}
        >
          <h2>{L.modules.title}</h2>

          <p class="path">{L.modules.basePath}: {effectiveModuleDir}</p>

          {#if modulesError}
            <p class="error">{modulesError}</p>
          {/if}
          {#if modulesLoading && modules.length === 0}
            <p class="hint">Loading...</p>
          {/if}

          {#if !modulesLoading && modules.length === 0 && !modulesError}
            <p class="hint">{L.modules.empty}</p>
          {/if}

          {#if !modulesLoading && modules.length > 0}
            <div class="module-list">
              {#each modules as m (m.name)}
                <div class="module-row">
                  <div class="module-info">
                    <span class="module-name">{m.name}</span>
                    <label class="switch {m.disabledByFlag ? 'disabled' : ''}">
                      <input
                        type="checkbox"
                        checked={m.disabledByFlag ? false : !m.skipMount}
                        disabled={m.disabledByFlag || m.toggling}
                        on:change={(e) => {
                          if (!m.disabledByFlag) toggleSkipMount(e,m);
                        }}
                      />
                      <span class="slider"></span>
                    </label>
                  </div>


                  {#if m.error}
                    <div class="error small">{m.error}</div>
                  {/if}
                </div>
              {/each}
            </div>
          {/if}

          <div class="actions" style="margin-top: 20px">
            <button type="button" on:click|preventDefault={loadModules} disabled={modulesLoading}>
              {modulesLoading ? 'Loading...' : L.modules.reload}
            </button>
          </div>
        </div>

      {:else}
        <div
          class="card"
          in:fade={{ duration: 180 }}
          out:fade={{ duration: 180 }}
        >
          <h2>{L.logs.title}</h2>

          <div class="field">
            <label for="log-select">{L.logs.select}</label>
            <div class="log-select-row">
              <select id="log-select" bind:value={logSelection}>
                <option value="current">{L.logs.current}</option>
                <option value="old">{L.logs.old}</option>
              </select>

              <button type="button" class="refresh-btn" on:click|preventDefault={loadLog} disabled={logLoading}>
                {logLoading ? 'Loading...' : L.logs.refresh}
              </button>
            </div>
          </div>

          {#if logError}
            <p class="error">{logError}</p>
          {/if}

          <pre class="log-view">{logLoading && !logContent ? 'Loading...' : logContent || L.logs.empty}</pre>
        </div>
      {/if}
    {/key}
  </div>

  <div class="bottom-bar">
    <button
      type="button"
      class="tab-btn {activeTab === 'config' ? 'active' : ''}"
      on:click|preventDefault={() => switchTab('config')}
    >
      {L.tabs.config}
    </button>

    <button
      type="button"
      class="tab-btn {activeTab === 'module' ? 'active' : ''}"
      on:click|preventDefault={() => switchTab('module')}
    >
      {L.tabs.modules}
    </button>

    <button
      type="button"
      class="tab-btn {activeTab === 'log' ? 'active' : ''}"
      on:click|preventDefault={() => switchTab('log')}
    >
      {L.tabs.logs}
    </button>
  </div>

</div>

<style>
  /* Component-specific styles only if needed */
</style>

// webui/src/App.tsx
import React, { useEffect, useState } from "react";
import { exec } from "kernelsu";
import locate from "./locate.json";
import "./index.css";

type Lang = keyof typeof locate; // "en" | "zh"
type Tab = "config" | "log";

type ConfigState = {
  moduledir: string;
  tempdir: string;
  mountsource: string;
  logfile: string;
  verbose: boolean;
  partitions: string[];
};

const DEFAULT_CONFIG: ConfigState = {
  moduledir: "/data/adb/modules",
  tempdir: "",
  mountsource: "KSU",
  logfile: "/data/adb/magic_mount/mm.log",
  verbose: false,
  partitions: [],
};

const CONFIG_PATH = "/data/adb/magic_mount/mm.conf";

const App: React.FC = () => {
  // ---------- i18n ----------
  const [lang, setLang] = useState<Lang>(() => {
    if (typeof window === "undefined") return "en";
    const saved = window.localStorage.getItem("mm-lang");
    return saved === "zh" || saved === "en" ? (saved as Lang) : "en";
  });
  const L = locate[lang];

  const handleLangChange = (e: React.ChangeEvent<HTMLSelectElement>) => {
    const value = e.target.value as Lang;
    setLang(value);
    if (typeof window !== "undefined") {
      window.localStorage.setItem("mm-lang", value);
    }
  };

  // ---------- tabs ----------
  const [activeTab, setActiveTab] = useState<Tab>("config");

  // ---------- config state ----------
  const [config, setConfig] = useState<ConfigState>(DEFAULT_CONFIG);
  const [configLoading, setConfigLoading] = useState(false);
  const [configSaving, setConfigSaving] = useState(false);
  const [configMessage, setConfigMessage] = useState<string | null>(null);

  // ---------- log state ----------
  type LogSelection = "current" | "old";
  const [logSelection, setLogSelection] = useState<LogSelection>("current");
  const [logContent, setLogContent] = useState("");
  const [logLoading, setLogLoading] = useState(false);
  const [logError, setLogError] = useState<string | null>(null);

  // ---------- partitions input ----------
  const [partitionInput, setPartitionInput] = useState("");

  // ---------- helpers ----------
  const isTrueValue = (v: string): boolean => {
    const s = v.trim().toLowerCase();
    return s === "1" || s === "true" || s === "yes" || s === "on";
  };

  const parseKvConfig = (text: string): ConfigState | null => {
    try {
      const result: ConfigState = { ...DEFAULT_CONFIG };
      const lines = text.split("\n");

      for (let line of lines) {
        line = line.trim();
        if (!line || line.startsWith("#")) continue;

        const eqIndex = line.indexOf("=");
        if (eqIndex < 0) {
          continue;
        }

        let key = line.slice(0, eqIndex).trim();
        let value = line.slice(eqIndex + 1).trim();

        if (!key || !value) continue;

        switch (key) {
          case "module_dir":
            result.moduledir = value;
            break;
          case "temp_dir":
            result.tempdir = value;
            break;
          case "mount_source":
            result.mountsource = value;
            break;
          case "log_file":
            result.logfile = value;
            break;
          case "debug":
            result.verbose = isTrueValue(value);
            break;
          case "partitions":
            result.partitions = value
              .split(",")
              .map((s) => s.trim())
              .filter((s) => s.length > 0);
            break;
          default:
            // unknown key: ignore
            break;
        }
      }

      return result;
    } catch (e) {
      console.error("Failed to parse config:", e);
      return null;
    }
  };

  const serializeKvConfig = (cfg: ConfigState): string => {
    const lines: string[] = ["# Magic Mount Configuration File", "# Generated by Web UI", ""];

    const moduleDir = cfg.moduledir || DEFAULT_CONFIG.moduledir;
    const mountSource = cfg.mountsource || DEFAULT_CONFIG.mountsource;
    const logFile = cfg.logfile || DEFAULT_CONFIG.logfile;

    lines.push(`module_dir=${moduleDir}`);

    if (cfg.tempdir) {
      lines.push(`temp_dir=${cfg.tempdir}`);
    }

    lines.push(`mount_source=${mountSource}`);

    if (logFile) {
      lines.push(`log_file=${logFile}`);
    }

    lines.push(`debug=${cfg.verbose ? "true" : "false"}`);

    if (cfg.partitions.length > 0) {
      lines.push(`partitions=${cfg.partitions.join(",")}`);
    }

    return lines.join("\n");
  };

  // ---------- read config ----------
  const loadConfig = async () => {
    setConfigLoading(true);
    setConfigMessage(null);

    try {
      const { errno, stdout, stderr } = await exec(
        `[ -f "${CONFIG_PATH}" ] && cat "${CONFIG_PATH}" || echo ""`,
      );

      if (errno !== 0) {
        console.error(stderr);
        setConfig(DEFAULT_CONFIG);
        setPartitionInput("");
        setConfigMessage(L.config.loadError);
        return;
      }

      if (!stdout.trim()) {
        setConfig(DEFAULT_CONFIG);
        setPartitionInput("");
        setConfigMessage(L.config.loadDefault);
        return;
      }

      const parsed = parseKvConfig(stdout);
      if (parsed) {
        setConfig(parsed);
        setPartitionInput(parsed.partitions.join(", "));
        setConfigMessage(L.config.loadSuccess);
      } else {
        setConfig(DEFAULT_CONFIG);
        setPartitionInput("");
        setConfigMessage(L.config.loadError);
      }
    } catch (e) {
      console.error(e);
      setConfig(DEFAULT_CONFIG);
      setPartitionInput("");
      setConfigMessage(L.config.loadError);
    } finally {
      setConfigLoading(false);
    }
  };

  // ---------- save config ----------
  const saveConfig = async () => {
    setConfigSaving(true);
    setConfigMessage(null);

    try {
      const partitions = partitionInput
        .split(",")
        .map((s) => s.trim())
        .filter((s) => s);

      const configToSave: ConfigState = { ...config, partitions };

      const content = serializeKvConfig(configToSave);
      const escapedContent = content.replace(/'/g, "'\\''");

      const shell = `
        mkdir -p "$(dirname "${CONFIG_PATH}")" && \
        printf '%s\n' '${escapedContent}' > "${CONFIG_PATH}"
      `;

      const { errno, stderr } = await exec(shell);

      if (errno !== 0) {
        console.error(stderr);
        setConfigMessage(L.config.saveFailed);
      } else {
        setConfig(configToSave);
        setConfigMessage(L.config.saveSuccess);
      }
    } catch (e) {
      console.error(e);
      setConfigMessage(L.config.saveError);
    } finally {
      setConfigSaving(false);
    }
  };

  // ---------- read log ----------
  const loadLog = async () => {
    setLogLoading(true);
    setLogError(null);
    setLogContent("");
    try {
      const basePath = config.logfile || DEFAULT_CONFIG.logfile;
      const fullPath = logSelection === "current" ? basePath : `${basePath}.old`;

      const { errno, stdout, stderr } = await exec(
        `[ -f "${fullPath}" ] && cat "${fullPath}" || echo "Log file not found"`,
      );

      if (errno !== 0) {
        console.error(stderr);
        setLogError(L.logs.readFailed + ` (errno=${errno})`);
      } else {
        setLogContent(stdout || "");
      }
    } catch (e) {
      console.error(e);
      setLogError(L.logs.readException);
    } finally {
      setLogLoading(false);
    }
  };

  // initial load config
  useEffect(() => {
    loadConfig();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // reload log when tab or file changed
  useEffect(() => {
    if (activeTab === "log") {
      loadLog();
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [activeTab, logSelection, config.logfile]);

  // ---------- render tabs ----------

  const renderConfigTab = () => (
    <div className="card">
      <h2>{L.config.title}</h2>

      {configLoading && <p className="hint">Loading...</p>}
      {configMessage && <p className="hint">{configMessage}</p>}

      {/* Verbose switch */}
      <div className="field">
        <label>{L.config.verboseLabel}</label>
        <div className="loglevel-switch">
          <button
            className={!config.verbose ? "lv-btn active" : "lv-btn"}
            onClick={() =>
              setConfig((prev) => ({
                ...prev,
                verbose: false,
              }))
            }
          >
            {L.config.verboseOff}
          </button>
          <button
            className={config.verbose ? "lv-btn active" : "lv-btn"}
            onClick={() =>
              setConfig((prev) => ({
                ...prev,
                verbose: true,
              }))
            }
          >
            {L.config.verboseOn}
          </button>
        </div>
      </div>

      {/* Module Directory */}
      <div className="field">
        <label>{L.config.moduleDir}</label>
        <input
          type="text"
          value={config.moduledir}
          placeholder={DEFAULT_CONFIG.moduledir}
          onChange={(e) =>
            setConfig((prev) => ({
              ...prev,
              moduledir: e.target.value,
            }))
          }
        />
      </div>

      {/* Temp Directory */}
      <div className="field">
        <label>{L.config.tempDir}</label>
        <input
          type="text"
          value={config.tempdir}
          placeholder="(auto-select if empty)"
          onChange={(e) =>
            setConfig((prev) => ({
              ...prev,
              tempdir: e.target.value,
            }))
          }
        />
      </div>

      {/* Mount Source */}
      <div className="field">
        <label>{L.config.mountSource}</label>
        <input
          type="text"
          value={config.mountsource}
          placeholder={DEFAULT_CONFIG.mountsource}
          onChange={(e) =>
            setConfig((prev) => ({
              ...prev,
              mountsource: e.target.value,
            }))
          }
        />
      </div>

      {/* Log File */}
      <div className="field">
        <label>{L.config.logFile}</label>
        <input
          type="text"
          value={config.logfile}
          placeholder={DEFAULT_CONFIG.logfile}
          onChange={(e) =>
            setConfig((prev) => ({
              ...prev,
              logfile: e.target.value,
            }))
          }
        />
      </div>

      {/* Partitions */}
      <div className="field">
        <label>{L.config.partitions}</label>
        <input
          type="text"
          value={partitionInput}
          placeholder="mi_ext,my_stock"
          onChange={(e) => setPartitionInput(e.target.value)}
        />
      </div>

      <div className="actions">
        <button onClick={loadConfig} disabled={configLoading || configSaving}>
          {L.config.reload}
        </button>
        <button className="primary" onClick={saveConfig} disabled={configSaving || configLoading}>
          {configSaving ? "Saving..." : L.config.save}
        </button>
      </div>

      <p className="path">
        {L.config.pathLabel}: {CONFIG_PATH}
      </p>
    </div>
  );

  const renderLogTab = () => {
    return (
      <div className="card">
        <h2>{L.logs.title}</h2>

        <div className="field">
          <label>{L.logs.select}</label>
          <div className="log-select-row">
            <select
              value={logSelection}
              onChange={(e) => setLogSelection(e.target.value as LogSelection)}
            >
              <option value="current">{L.logs.current}</option>
              <option value="old">{L.logs.old}</option>
            </select>

            <button className="refresh-btn" onClick={loadLog} disabled={logLoading}>
              {logLoading ? "Loading..." : L.logs.refresh}
            </button>
          </div>
        </div>

        {logError && <p className="error">{logError}</p>}

        <pre className="log-view">
          {logLoading && !logContent ? "Loading..." : logContent || L.logs.empty}
        </pre>
      </div>
    );
  };

  return (
    <div className="app-root">
      {/* top bar with language selector */}
      <div className="top-bar">
        <div className="title">Magic Mount</div>

        <select className="lang-select" value={lang} onChange={handleLangChange}>
          <option value="en">English</option>
          <option value="zh">中文</option>
        </select>
      </div>

      <div className="app-main">{activeTab === "config" ? renderConfigTab() : renderLogTab()}</div>

      {/* bottom tabs */}
      <div className="bottom-bar">
        <button
          className={activeTab === "config" ? "tab-btn active" : "tab-btn"}
          onClick={() => setActiveTab("config")}
        >
          {L.tabs.config}
        </button>
        <button
          className={activeTab === "log" ? "tab-btn active" : "tab-btn"}
          onClick={() => setActiveTab("log")}
        >
          {L.tabs.logs}
        </button>
      </div>
    </div>
  );
};

export default App;
