// webui/src/routes/ModulesTab.svelte
<script>
  import { store } from '../lib/store.svelte';
  import { ICONS } from '../lib/constants';
  import { onMount } from 'svelte';
  import { slide } from 'svelte/transition';
  import Skeleton from '../components/Skeleton.svelte';
  import './ModulesTab.css';
  let searchQuery = $state('');
  let filterType = $state('all');
  let expandedMap = $state({}); 
  onMount(() => {
    store.loadModules();
  });
  let filteredModules = $derived(store.modules.filter(m => {
    const q = searchQuery.toLowerCase();
    const matchSearch = m.name.toLowerCase().includes(q) || m.id.toLowerCase().includes(q);
    const matchFilter = filterType === 'all' || m.mode === filterType;
    return matchSearch && matchFilter;
  }));
  function toggleExpand(id) {
    if (expandedMap[id]) {
      delete expandedMap[id];
    } else {
      expandedMap[id] = true;
    }
    expandedMap = { ...expandedMap };
  }
  function handleKeydown(e, id) {
    if (e.key === 'Enter' || e.key === ' ') {
      e.preventDefault();
      toggleExpand(id);
    }
  }
</script>
<div class="md3-card" style="padding: 16px;">
  <p style="margin: 0; font-size: 14px; color: var(--md-sys-color-on-surface-variant); line-height: 1.5;">
    {store.L.modules.desc}
  </p>
</div>
<div class="search-container">
  <svg class="search-icon" viewBox="0 0 24 24"><path d={ICONS.search} /></svg>
  <input 
    type="text" 
    class="search-input" 
    placeholder={store.L.modules.searchPlaceholder}
    bind:value={searchQuery}
  />
  <div class="filter-controls">
    <span style="font-size: 12px; color: var(--md-sys-color-on-surface-variant);">{store.L.modules.filterLabel}</span>
    <select class="filter-select" bind:value={filterType}>
      <option value="all">{store.L.modules.filterAll}</option>
      <option value="auto">{store.L.modules.modeAuto}</option>
      <option value="magic">{store.L.modules.modeMagic}</option>
    </select>
  </div>
</div>
{#if store.loading.modules}
  <div class="rules-list">
    {#each Array(5) as _}
      <div class="rule-card">
        <div class="rule-info">
          <div style="display:flex; flex-direction:column; gap: 6px; width: 100%;">
            <Skeleton width="60%" height="20px" />
            <Skeleton width="40%" height="14px" />
          </div>
        </div>
        <Skeleton width="120px" height="40px" borderRadius="4px" />
      </div>
    {/each}
  </div>
{:else if filteredModules.length === 0}
  <div style="text-align:center; padding: 40px; opacity: 0.6">
    {store.modules.length === 0 ? store.L.modules.empty : "No matching modules"}
  </div>
{:else}
  <div class="rules-list">
    {#each filteredModules as mod (mod.id)}
      <div 
        class="rule-card" 
        class:expanded={expandedMap[mod.id]} 
        onclick={() => toggleExpand(mod.id)}
        onkeydown={(e) => handleKeydown(e, mod.id)}
        role="button"
        tabindex="0"
      >
        <div class="rule-main">
          <div class="rule-info">
            <div style="display:flex; flex-direction:column;">
              <span class="module-name">{mod.name}</span>
              <span class="module-id">{mod.id} <span style="opacity:0.6; margin-left: 8px;">{mod.version}</span></span>
            </div>
          </div>
          <div class="mode-badge {mod.mode === 'magic' ? 'badge-magic' : 'badge-auto'}">
            {mod.mode === 'magic' ? store.L.modules.modeMagic : store.L.modules.modeAuto}
          </div>
        </div>
        {#if expandedMap[mod.id]}
          <div class="rule-details" transition:slide={{ duration: 200 }}>
            <p class="module-desc">{mod.description || 'No description'}</p>
            <p class="module-meta">Author: {mod.author || 'Unknown'}</p>
            <div class="config-section">
              <div class="config-row">
                <span class="config-label">{store.L.config.title}:</span>
                <div 
                  class="text-field compact-select"
                  onclick={(e) => e.stopPropagation()}
                  onkeydown={(e) => e.stopPropagation()}
                  role="group"
                  tabindex="-1"
                >
                  <select bind:value={mod.mode}>
                    <option value="auto">{store.L.modules.modeAuto}</option>
                    <option value="magic">{store.L.modules.modeMagic}</option>
                  </select>
                </div>
              </div>
            </div>
          </div>
        {/if}
      </div>
    {/each}
  </div>
{/if}
<div class="bottom-actions">
  <button class="btn-tonal" onclick={() => store.loadModules()} disabled={store.loading.modules} title={store.L.modules.reload}>
    <svg viewBox="0 0 24 24" width="20" height="20"><path d={ICONS.refresh} fill="currentColor"/></svg>
  </button>
  <button class="btn-filled" onclick={() => store.saveModules()} disabled={store.saving.modules}>
    <svg viewBox="0 0 24 24" width="18" height="18"><path d={ICONS.save} fill="currentColor"/></svg>
    {store.saving.modules ? store.L.common.saving : store.L.modules.save}
  </button>
</div>

// webui/src/routes/ModulesTab.tsx
/**
 * Copyright 2025 Magic Mount-rs Authors SPDX-License-Identifier:
 * GPL-3.0-or-later
 */

import { For, Show, createMemo, createSignal, onMount } from "solid-js";

import BottomActions from "../components/BottomActions";
import Skeleton from "../components/Skeleton";
import { ICONS } from "../lib/constants";
import { store } from "../lib/store";

import "./ModulesTab.css";
import "@material/web/iconbutton/filled-tonal-icon-button.js";
import "@material/web/button/filled-button.js";
import "@material/web/icon/icon.js";

export default function ModulesTab() {
  const [searchQuery, setSearchQuery] = createSignal("");
  const [expandedId, setExpandedId] = createSignal<string | null>(null);

  onMount(() => {
    store.loadModules();
  });

  const filteredModules = createMemo(() =>
    store.modules.filter((m) => {
      const q = searchQuery().toLowerCase();
      const matchSearch =
        m.name.toLowerCase().includes(q) || m.id.toLowerCase().includes(q);

      return matchSearch;
    }),
  );

  function toggleExpand(id: string) {
    setExpandedId(expandedId() === id ? null : id);
  }

  const getModeLabel = (isMounted: boolean) =>
    isMounted ? "Mounted" : "Unmounted";

  const getModeClass = (isMounted: boolean) =>
    isMounted ? "mode-mounted" : "mode-unmounted";

  return (
    <>
      <div class="modules-page">
        <div class="header-section">
          <div class="search-bar">
            <svg class="search-icon" viewBox="0 0 24 24">
              <path d={ICONS.search} />
            </svg>
            <input
              type="text"
              class="search-input"
              placeholder={store.L.modules.searchPlaceholder}
              value={searchQuery()}
              onInput={(e) => setSearchQuery(e.currentTarget.value)}
            />
          </div>
        </div>

        <div class="modules-list">
          <Show
            when={!store.loading.modules}
            fallback={
              <For each={Array.from({ length: 6 })}>
                {() => <Skeleton height="64px" borderRadius="16px" />}
              </For>
            }
          >
            <Show
              when={filteredModules().length > 0}
              fallback={
                <div class="empty-state">
                  <div class="empty-icon">
                    <md-icon>
                      <svg viewBox="0 0 24 24">
                        <path d={ICONS.modules} />
                      </svg>
                    </md-icon>
                  </div>
                  <p>
                    {store.modules.length === 0
                      ? store.L.modules.empty
                      : "No matching modules"}
                  </p>
                </div>
              }
            >
              <For each={filteredModules()}>
                {(mod) => (
                  <div
                    class={`module-card ${expandedId() === mod.id ? "expanded" : ""} ${mod.is_mounted ? "" : "unmounted"}`}
                  >
                    <div
                      class="module-header"
                      onClick={() => toggleExpand(mod.id)}
                      role="button"
                      tabIndex={0}
                      onKeyDown={(e) =>
                        (e.key === "Enter" || e.key === " ") &&
                        toggleExpand(mod.id)
                      }
                    >
                      <div class="module-info">
                        <div class="module-name">{mod.name}</div>
                        <div class="module-meta">
                          <span class="module-id">{mod.id}</span>
                          <span class="version-badge">{mod.version}</span>
                        </div>
                      </div>
                      <div
                        class={`mode-indicator ${getModeClass(mod.is_mounted)}`}
                      >
                        {getModeLabel(mod.is_mounted)}
                      </div>
                    </div>

                    <div class="module-body-wrapper">
                      <div class="module-body-inner">
                        <div class="module-body-content">
                          <div class="body-section">
                            <div class="section-label">
                              {store.L.modules.descriptionLabel}
                            </div>
                            <p class="module-desc">
                              {mod.description ||
                                store.L.modules.noDescriptionLabel}
                            </p>
                          </div>

                          <div class="body-section">
                            <div class="section-label">
                              {store.L.modules.authorLabel}
                            </div>
                            <div class="module-author">
                              {mod.author || store.L.modules.unknownLabel}
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                )}
              </For>
            </Show>
          </Show>
        </div>
      </div>

      <BottomActions>
        <div class="spacer" />
        <md-filled-tonal-icon-button
          onClick={() => store.loadModules()}
          title={store.L.modules.reload}
        >
          <md-icon>
            <svg viewBox="0 0 24 24">
              <path d={ICONS.refresh} />
            </svg>
          </md-icon>
        </md-filled-tonal-icon-button>
      </BottomActions>
    </>
  );
}
