// webui/src/ui/md3/components/ChipInput.vue
<!--
Copyright (C) 2026 meta-magic_mount-rs developers
SPDX-License-Identifier: GPL-v3
-->

<script setup lang="ts">
import { ref } from "vue";
import { ICONS } from "../icons";

const props = defineProps<{
  values: string[];
  placeholder?: string;
}>();

const emit = defineEmits<{
  (e: "update:values", values: string[]): void;
}>();

const inputValue = ref("");

function handleAdd() {
  const value = inputValue.value.trim();
  if (value && !props.values.includes(value)) {
    emit("update:values", [...props.values, value]);
    inputValue.value = "";
  }
}

function handleRemove(index: number) {
  emit(
    "update:values",
    props.values.filter((_, i) => i !== index),
  );
}

function handleKeydown(e: KeyboardEvent) {
  if (e.key === "Enter") {
    e.preventDefault();
    handleAdd();
  }
}
</script>

<template>
  <div class="chip-input-wrapper">
    <div v-if="values.length > 0" class="chip-set">
      <div v-for="(value, index) in values" :key="index" class="chip-item">
        <span class="chip-text">{{ value }}</span>
        <button class="chip-remove" @click="handleRemove(index)">
          <svg viewBox="0 0 24 24" width="28" height="28">
            <path :d="ICONS.delete" />
          </svg>
        </button>
      </div>
    </div>
    <div class="input-row">
      <input
        v-model="inputValue"
        :placeholder="placeholder"
        class="chip-input-field"
        @keydown="handleKeydown"
      />
      <button class="add-btn" @click="handleAdd">
        <svg viewBox="0 0 24 24" width="20" height="20">
          <path :d="ICONS.add" />
        </svg>
      </button>
    </div>
  </div>
</template>

<style scoped>
.chip-input-wrapper {
  display: flex;
  flex-direction: column;
  padding: 12px;
  border: 1px solid var(--md-sys-color-outline);
  border-radius: 8px;
}

.chip-set {
  display: flex;
  flex-wrap: wrap;
  gap: 8px;
  margin-bottom: 8px;
}

.chip-item {
  display: flex;
  align-items: center;
  gap: 6px;
  padding: 6px 10px;
  background-color: var(--md-sys-color-secondary-container);
  color: var(--md-sys-color-on-secondary-container);
  border-radius: 16px;
  font-size: 14px;
}

.chip-remove {
  width: 28px;
  height: 28px;
  border: none;
  background: transparent;
  display: flex;
  align-items: center;
  justify-content: center;
  cursor: pointer;
  color: inherit;
}

.input-row {
  display: flex;
  align-items: center;
  gap: 8px;
}

.chip-input-field {
  flex: 1;
  min-width: 80px;
  border: none;
  background: transparent;
  font-size: 16px;
  color: var(--md-sys-color-on-surface);
  outline: none;
  height: 32px;
}

.add-btn {
  width: 32px;
  height: 32px;
  border: none;
  background: transparent;
  display: flex;
  align-items: center;
  justify-content: center;
  color: var(--md-sys-color-primary);
  cursor: pointer;
}
</style>

// webui/src/components/ChipInput.tsx
/**
 * Copyright 2025 Meta-Hybrid Mount Authors SPDX-License-Identifier:
 * GPL-3.0-or-later
 */

import { For, Show, createSignal } from "solid-js";

import "@material/web/chips/chip-set.js";
import "@material/web/chips/input-chip.js";
import "@material/web/icon/icon.js";
import "@material/web/iconbutton/icon-button.js";
import "./ChipInput.css";

interface Props {
  values: string[];
  placeholder?: string;
  onValuesChange: (newValues: string[]) => void;
}

export default function ChipInput(props: Props) {
  const [inputValue, setInputValue] = createSignal("");

  function handleKeyDown(e: KeyboardEvent) {
    if (e.key === "Enter" || e.key === "," || e.key === " ") {
      e.preventDefault();
      addChip();
    } else if (
      e.key === "Backspace" &&
      inputValue() === "" &&
      props.values.length > 0
    ) {
      removeChip(props.values.length - 1);
    }
  }

  function addChip() {
    const val = inputValue().trim();
    if (val) {
      if (!props.values.includes(val)) {
        const newValues = [...props.values, val];
        props.onValuesChange(newValues);
      }
      setInputValue("");
    }
  }

  function removeChip(index: number) {
    const newValues = props.values.filter((_, i) => i !== index);
    props.onValuesChange(newValues);
  }

  return (
    <div class="chip-input-wrapper">
      <md-chip-set
        classList={{ "chip-set-has-values": props.values.length > 0 }}
      >
        <For each={props.values}>
          {(val, i) => (
            <md-input-chip
              label={val}
              remove-only
              on:remove={() => removeChip(i())}
            />
          )}
        </For>
      </md-chip-set>

      <div class="input-row">
        <input
          type="text"
          class="chip-input-field"
          value={inputValue()}
          onInput={(e) => setInputValue(e.currentTarget.value)}
          onKeyDown={handleKeyDown}
          onBlur={addChip}
          placeholder={props.placeholder ?? "Add item..."}
          enterkeyhint="done"
        />
        <Show when={inputValue().trim().length > 0}>
          <md-icon-button onClick={addChip} class="add-btn" title="Add tag">
            <md-icon>
              <svg viewBox="0 0 24 24">
                <path d="M9 16.2L4.8 12l-1.4 1.4L9 19 21 7l-1.4-1.4L9 16.2z" />
              </svg>
            </md-icon>
          </md-icon-button>
        </Show>
      </div>
    </div>
  );
}
